spring:
  servlet:
    multipart:
      enabled: true
      #单个文件的大小
      max-file-size: 1MB
      #总数据的大小
      max-request-size: 1MB
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimeZone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:

    # 整合mybatis
mybatis:
  type-aliases-package: com.wang.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
