person:
  name: ${random.uuid}@qq.com
  age: ${random.int(100)}
  happy: true
  birth: 1997/03/05
  hello: 嗡嗡嗡
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - music
    - sports
  dog:
    name: ${person.hello:hello}_旺财
dog:
  first-name: 大黄
  age: 3


server:
  port: 8080
spring:
  profiles:
    ##多环境配置
    active: test

---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: test